version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.8.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Running testing"
          command: echo "Running testing"
  
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Running deployment"
          command: echo "Running deployment"


workflows: 
  version: 2
  build-and-deploy:
    jobs:
      - build
  schedule-workflow:
    triggers:
      - schedule: 
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - deploy