version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.8.0
        environment:
          TEST_DATABASE_URL: postgres://postgres@localhost:5432/circleci_test
      - image: circleci/postgres
    steps:
      - checkout
      - run:
          name: WHO_AM_I
          command: whoami