version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:23.8.0
        environment:
          TEST_DATABASE_URL: postgres://root@localhost:5432/circleci_test
      - image: cimg/postgres:15.3
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password  # ✅ Add a password
          POSTGRES_DB: circleci_test   # ✅ Set default DB (optional)
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - run:
          name: "Check Who am i"
          command: whoami
      - run:
          name: "Create table"
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "Create table test (name char(15));"
      - run:
      