version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.8.0
        environment:
          TEST_DATABASE_URL: postgres://root@localhost:5432/circleci_test
      - image: cimg/postgres:15.3
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password  # ✅ Add a password
          POSTGRES_DB: circleci_test   # ✅ Set default DB (optional)
    steps:
      - checkout
      - run:
          name: install psql
          command: sudo apt install postgresql-client-9.6
      - run:
          name: WHO_AM_I
          command: whoami
      - run: 
          name: "Create Table"
          command: |
            psql -d $TEST_DATABASE_URL -c "CREATE table test (name char(15));"
      - run:
          name: "insert into table"
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "INSERT INTO test (name) VALUES ('Sachin');"
      - run:
          name: "select from table"
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "SELECT * FROM test;"